### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by trebmuh** [buxx/muzich#1]
I though that having this link somewhere in the repo could be useful for a bunch of people, so here it is: https://linuxfr.org/news/liberation-du-code-source-de-muzi-ch-quelle-licence (in French).

**Comment by buxx** [comment]
Good idea ! I updated README:

* 38cc5529af3c7c96f3f3b63ecbc92088cd1a54d0
* 9aeb15e6d33ac64371c033b97a05946c1322d310
